### ISSUE TITLE
Add getting started guide, to quickly help new comers to play with the bot

### ISSUE THREAD

**Issue by aboullaite** [fbdevelopercircles/open-source-edu-bot#1]
The readme describe very well how to get the app running, however it doesn't describe how to integrate it with messenger nor how to test the bot. We need to add documentation to cover this part

**Comment by PrashanthPuneriya** [comment]
@aboullaite Can you point me to the resources to learn about this?

**Comment by aboullaite** [comment]
@PrashanthPuneriya something like this one https://developers.facebook.com/docs/messenger-platform/getting-started/sample-apps/original-coast-clothing#deploy

**Comment by vj-codes** [comment]
heyy I would like to fix this @aboullaite @elinguiuriel 
how is this different from #7 ?

**Comment by aboullaite** [comment]
@vj-codes you can consider this one as a sub-issue of #7! Check the link i mentionned above, and  feel free to submit. A PE

**Comment by vj-codes** [comment]
@aboullaite Can the title be 'Setting up your Messenger App' and the content is placed before installation in readme?
