### ISSUE TITLE
Remove unneeded punctuation in Git install prompt

### ISSUE THREAD

**Issue by caabernathy** [fbdevelopercircles/open-source-edu-bot#10]
#### Describe the bug
The snippet inviting you to install git has an unneeded punctuation at the end.

#### To Reproduce
1. Answer questions from the bot that you know about open source, are not familiar with version control, and that you would like to get started with Git.
2. Tap Install Git and check out the next prompt.
3. After the exclamation mark there is an unnecessary period.

#### Expected behavior
There should not be a period at the end.

#### Screenshots
![Screen Shot 2020-07-16 at 9 01 28 AM](https://user-images.githubusercontent.com/691109/87680435-0c38b280-c743-11ea-8f59-f56975a3268e.png)

**Comment by vj-codes** [comment]
Heyy @caabernathy I would like to fix this

**Comment by aboullaite** [comment]
@vj-codes please go ahead 🙏 thanks for your help
