### ISSUE TITLE
Add email replacement to Git configure step

### ISSUE THREAD

**Issue by caabernathy** [fbdevelopercircles/open-source-edu-bot#12]
#### The problem
The Configure Git steps mention replacing the name in the example but doesn't mention replacing the email. 

#### Describe the solution you'd like
I suggest making the email replacement a specific instruction.

#### Screenshot
![Screen Shot 2020-07-16 at 9 11 53 AM](https://user-images.githubusercontent.com/691109/87681917-d7c5f600-c744-11ea-8d7a-48b6a3e86e49.png)

**Comment by PrashanthPuneriya** [comment]
@caabernathy @elinguiuriel I would like to work on this issue.

**Comment by aboullaite** [comment]
Awesome @PrashanthPuneriya🎉! I assigned it to you 🙏 do not hesitate to ping us for any clarifications.

Looking forward to your PR.

**Comment by vj-codes** [comment]
@aboullaite Can I fix this too if the person assigned has not created a PR yet?

**Comment by aboullaite** [comment]
@vj-codes i think @PrashanthPuneriya is working on it! Let's give him more time :)

**Comment by vj-codes** [comment]
> @vj-codes i think @PrashanthPuneriya is working on it! Let's give him more time :)

Yes sure:)

**Comment by PrashanthPuneriya** [comment]
@aboullaite I could create a PR right now without understanding the codebase. But, I am learning bit by bit about GraphQL and messenger bot to get a greater understanding of the codebase. So, it is taking me longer than anticipated to create a PR.
@vj-codes I will inform you when I don't expect myself of creating a PR.

**Comment by aboullaite** [comment]
Hey @PrashanthPuneriya, graphql is great, but i dont see why ypu need it here ?

**Comment by PrashanthPuneriya** [comment]
@aboullaite Oh! Don't we need it here? I came across `webhooks` and `tokens` terms within this project. So, I thought of learning GraphQL as well. Anyway,
I learned GraphQL not knowing that we won't require them in this project. There is no harm in learning. :)

**Comment by aboullaite** [comment]
@PrashanthPuneriya absolutely! Just wanted to know if I missed something 👍
