### ISSUE TITLE
Bug: Failed to find Flask application or factory in module "wsgi".

### ISSUE THREAD

**Issue by PrashanthPuneriya** [fbdevelopercircles/open-source-edu-bot#20]
#### Describe the bug
After setting up the project as described in the [docs](https://github.com/fbdevelopercircles/open-source-edu-bot#using-a-virtual-environment). When I try to run using `flask run` command it throws error as follows:-

> Error: Failed to find Flask application or factory in module "wsgi". Use "FLASK_APP=wsgi:name to specify one.

#### To Reproduce
1. Set up the project as described in the [docs](https://github.com/fbdevelopercircles/open-source-edu-bot#using-a-virtual-environment).
2. Run `flask run` command.
3. See the error.

#### Expected behavior
The application should start running on defined port without throwing any errors

#### Screenshots
![Screenshot from 2020-07-17 18-40-13](https://user-images.githubusercontent.com/42068010/87789730-2070d280-c85d-11ea-8627-c17029def6a2.png)

**Comment by aboullaite** [comment]
@elinguiuriel any thoughts ?

**Comment by PrashanthPuneriya** [comment]
> @elinguiuriel any thoughts ?

@aboullaite Sorry for creating a PR before discussing. Didn't get your comment notification. Also please review the PR.

**Comment by aboullaite** [comment]
@PrashanthPuneriya it's fine! I've asked review from @elinguiuriel as he's the one who put it first, probably he can add more insight.
Thank you for reporting and suggesting a quick fix 🙏
