### ISSUE TITLE
Improve installation documentation in Readme

### ISSUE THREAD

**Issue by vj-codes** [fbdevelopercircles/open-source-edu-bot#48]
#### Describe the bug
1)For Windows cmd users -
cp .sample.env .env should be changed to **copy .sample.env .env** 

2)For Windows cmd users -
export FLASK_APP fbosbot ,export FLASK_RUN_HOST 0.0.0.0 ,export FLASK_ENV development
should be changed to
**set FLASK_APP fbosbot
set FLASK_RUN_HOST 0.0.0.0
set FLASK_ENV development**

#### To Reproduce
1. Go to Readme >>Installation
2. See error

**Comment by vj-codes** [comment]
@aboullaite @caabernathy I faced this while setting up the repo.
Can I work on this?

**Comment by aboullaite** [comment]
For 1) i thing a better wording would be to advice to rename the file instead of using *unix commands! 
For 2) i suggest to add a windows section.

Thanks for reporting this, feel free to submit a fix 🙏

**Comment by vj-codes** [comment]
@aboullaite Didn't get you for first one?Can you explain again please , I'm new here which file should be changed?

**Comment by aboullaite** [comment]
Your approach in the first one is valid! My suggestion is to replace the copy word by rename the file to `.env`
