### ISSUE TITLE
`Discover Github` attachment  does not appear

### ISSUE THREAD

**Issue by aboullaite** [fbdevelopercircles/open-source-edu-bot#49]
#### Describe the bug
Discover Github attachment doesn't appear when user click `next` quick reply in Github track
<img width="602" alt="Screen Shot 2020-07-25 at 9 39 06 PM" src="https://user-images.githubusercontent.com/2836850/88465986-ab864400-cebf-11ea-8900-7f084414c11a.png">

#### To Reproduce
1. Choose Github Track
2. Hit `Next`
3. Nothing appears
#### Expected behavior
`Discover Github` should appear
#### Screenshots
<img width="953" alt="Screen Shot 2020-07-25 at 9 43 13 PM" src="https://user-images.githubusercontent.com/2836850/88466008-e1c3c380-cebf-11ea-8b1a-58e5032a5025.png">

**Comment by elinguiuriel** [comment]
@aboullaite  you tried to put 4 buttons in the template, the maximum number is 3:
https://developers.facebook.com/docs/messenger-platform/send-messages/template/generic


```
{
   "attachment":{
      "type":"template",
      "payload":{
         "template_type":"generic",
         "elements":[
            {
               "title":"Découvre GitHub",
               "image_url":"https://fb-os-bot.herokuapp.com/static/img/github.jpg",
               "subtitle":"Découvre le site officiel de GitHub, ou suis un tutoriel pour débutant",
               "buttons":[
                  {
                     "type":"web_url",
                     "title":"Site officiel",
                     "url":"https://github.com"
                  },
                  {
                     "type":"web_url",
                     "title":"Tutoriel GitHub",
                     "url":"https://guides.github.com/activities/hello-world/"
                  },
                  {
                     "type":"postback",
                     "title":"�\u200d� Make a PR",
                     "payload":"CONTR_1"
                  },
                  {
                     "type":"postback",
                     "title":"��\u200d♀️ Main Menu �️",
                     "payload":"MAIN_MENU"
                  }
               ]
            }
         ],
         "sharable":false
      }
   }
}
```

Delete the most irrelevant button and fix it the declaration [here](https://github.com/fbdevelopercircles/open-source-edu-bot/blob/aceff64d99dc2d9efd47535ca772bcb6657cc9e8/src/services/messenger.py#L366)
