### ISSUE TITLE
Delete ENV Export in README.md

### ISSUE THREAD

**Issue by elinguiuriel** [fbdevelopercircles/open-source-edu-bot#51]
No need to export environment variables, they are already defined in `.sample.env`

```bash
export FLASK_APP fbosbot
export FLASK_RUN_HOST 0.0.0.0
export FLASK_ENV development
```
We should delete this section !

**Comment by aboullaite** [comment]
I assume this should be deleted from the Readme file

**Comment by vj-codes** [comment]
hey @elinguiuriel can I fix this?

**Comment by aboullaite** [comment]
@vj-codes you're just on fire 🔥 . Assigned to you
