### ISSUE TITLE
ModuleNotFoundError : no module named 'fbosbot'

### ISSUE THREAD

**Issue by vj-codes** [fbdevelopercircles/open-source-edu-bot#58]
#### Describe the bug
When I follow the installation steps and run this error shows up

#### Expected behavior
The project should run locally 

#### Screenshots

![Screenshot (35)](https://user-images.githubusercontent.com/60894542/88659223-55e5ad80-d0f2-11ea-9f26-4a0c0dfc4e38.png)
![Screenshot (37)](https://user-images.githubusercontent.com/60894542/88659229-58480780-d0f2-11ea-9ccf-308aa719cd4a.png)

**Comment by elinguiuriel** [comment]
There is not root endpoint `/` in the app, and the app is not intend to be use as web app, try [localhost:5000/privacy.html](http://localhost:5000/privacy.html) and tel us if it works!

**Comment by aboullaite** [comment]
Thanks @elinguiuriel for the quick hint! I think we could fix this by adding a static page that point the user to the right setup! I think it will hep to avoid this in the future

**Comment by vj-codes** [comment]
> There is not root endpoint `/` in the app, and the app is not intend to be use as web app, try [localhost:5000/privacy.html](http://localhost:5000/privacy.html) and tel us if it works!
Didn't work @aboullaite @elinguiuriel

**Comment by elinguiuriel** [comment]
You didn't exactly follow the documentation, you have to be in the `src` folder before doing `flask run`

**Comment by vj-codes** [comment]
@elinguiuriel Thanks ,sorry my bad.I changed still the error persists. Do you think it might be due to the .env file?I have adapted it acc to the tokens generated except the 'FB_VERIFY_TOKEN' which I put randomly as I couldn't find any way to generate it.
![Screenshot (38)](https://user-images.githubusercontent.com/60894542/88686897-2dbb7600-d115-11ea-9b0e-1c3e94a8e219.png)

**Comment by mohitacecode** [comment]
I am facing the same error.

**Comment by elinguiuriel** [comment]
We have to revert this issue #51 because it cause problem on windows environments : 

```bash
export FLASK_APP fbosbot
export FLASK_RUN_HOST 0.0.0.0
export FLASK_ENV development
```

**Comment by aboullaite** [comment]
@elinguiuriel is the .env file not enough ? is there any specific command/libraries to make it work on windows and load env variables ?

**Comment by elinguiuriel** [comment]
`python-dotenv` should work but it seams to have issues finding the .env file on windows

**Comment by vj-codes** [comment]
> `python-dotenv` should work but it seams to have issues finding the .env file on windows

It works for my other similar repos on windows though I don't know why this one is causing problems.

**Comment by aboullaite** [comment]
@vj-codes can you help us investigate what the issue and probably a fix ?

**Comment by vj-codes** [comment]
Sure I'll be more than happy to! @aboullaite

**Comment by vj-codes** [comment]
@aboullaite It will be also helpful if issue #1 is fixed .Also can you confirm whether  'FB_VERIFY_TOKEN' is a random sting or has to generated?Thanks!

**Comment by vj-codes** [comment]
> @aboullaite It will be also helpful if issue #1 is fixed .Also can you confirm whether 'FB_VERIFY_TOKEN' is a random string or has to generated?Thanks!

**Comment by aboullaite** [comment]
You're right about `FB_VERIFY_TOKEN`

**Comment by aboullaite** [comment]
@elinguiuriel i suggest to keep this issue open until we find a fix for `.env` file on windows. Explicitly adding env variables was more or a quick fix than a sustainable solution

**Comment by PrashanthPuneriya** [comment]
@elinguiuriel @aboullaite @vj-codes @pixan198 Exporting the env variables **must** be done after you cd into `src`(root) folder. And my guess with `.env` file is that it should also be in `src`(root) folder/directory. Let me know if this fixed the issue.

**Comment by PrashanthPuneriya** [comment]
After following the above procedure mentioned in the previous comment of mine(above) try accessing the privacy url as @elinguiuriel said in [this comment](https://github.com/fbdevelopercircles/open-source-edu-bot/issues/58#issuecomment-665068854) to check if it has fixed this issue or not.

**Comment by aboullaite** [comment]
Can you submit a pr with the discussed fix ?

**Comment by pixan198** [comment]
@PrashanthPuneriya Thanks for the help :smiley: , your solution fixed this issue.

**Comment by PrashanthPuneriya** [comment]
> Can you submit a pr with the discussed fix ?

Okay! Will do it

**Comment by vj-codes** [comment]
@PrashanthPuneriya it worked!
@elinguiuriel @aboullaite I did not export variables but as it was mentioned in earlier comment by @PrashanthPuneriya just changed the location of .env file into src folder.My suggestion would be to do the same and remove the export variables section from Readme.md same as issue #51 as .env does the same and repeating might not be benificial as well as cause confusion.
How's that?

**Comment by vj-codes** [comment]
@aboullaite @elinguiuriel what I see after running is the privacy policy of chatbot , to test do I still need to do it through messenger?

**Comment by aboullaite** [comment]
@vj-codes yes! Now you're sure the app is up and running. You need to setup a page and link it
