### ISSUE TITLE
Error: Could not import "fbosbot".

### ISSUE THREAD

**Issue by pixan198** [fbdevelopercircles/open-source-edu-bot#61]
#### Describe the bug
This error shows up when I try to start the application using `flask run`

#### To Reproduce
1. Follow steps mentioned in [README.md](https://github.com/fbdevelopercircles/open-source-edu-bot/blob/master/README.md)
2. After compiling localization files run `flask run`
3. See Error

#### Expected behavior
The Project should run locally.

#### Screenshots

![bug](https://user-images.githubusercontent.com/56932286/88764922-600bb880-d193-11ea-9a5f-6907944cfbe3.PNG)

**Comment by elinguiuriel** [comment]
I reverted issue #51 as a quick fix, we will find a solution to resolve the problem after, but you can now run the app by reading the current READM.md file with environment variable exported manually!

**Comment by vj-codes** [comment]
@pixan198 environment should be development not production

**Comment by elinguiuriel** [comment]
By default the code is set for production, if you want to develop edit the variable and put `development`

**Comment by pixan198** [comment]
@elinguiuriel @vj-codes Thanks for the help, fixed it :sparkles: 
but getting the same error as in #58

**Comment by elinguiuriel** [comment]
@pixan198 you actually have to use

```
export FLASK_APP=fbosbot
export FLASK_RUN_HOST=0.0.0.0
export FLASK_ENV=development
```

we forget the `=` sign, you can have more information [here](https://flask.palletsprojects.com/en/1.1.x/tutorial/factory/)
