### ISSUE TITLE
Improper ENV syntax

### ISSUE THREAD

**Issue by vj-codes** [fbdevelopercircles/open-source-edu-bot#64]
#### Describe the bug
When I follow instructions in Readme.md to export ENV variables , they cannot be defined due to absence of equal to '=' sign.

#### Solution
Add an '=' sign .Screenshot below shows it works properly then.

#### Screenshots

![Screenshot (42)](https://user-images.githubusercontent.com/60894542/88822210-32e5f700-d1e1-11ea-8565-88c8aa78aee7.png)

**Comment by vj-codes** [comment]
@aboullaite hey this is a minor change , may I fix this?

**Comment by elinguiuriel** [comment]
got ahead please!

**Comment by vj-codes** [comment]
Quick ques :Will the '=' sign be required for non-windows user as I only use windows and don't know about other ones? @elinguiuriel

**Comment by elinguiuriel** [comment]
@vj-codes put `=` for both as you can see here : https://flask.palletsprojects.com/en/1.1.x/tutorial/factory/
