### ISSUE TITLE
Adding https://m.me/OpenSourceChatbot in README.md

### ISSUE THREAD

**Issue by elinguiuriel** [fbdevelopercircles/open-source-edu-bot#66]
The chatbot is deployed here : https://m.me/OpenSourceChatbot it will be good to have it in README.md so developers could test it before deploying it in the own page.

**Comment by vj-codes** [comment]
May I fix this? @elinguiuriel 
What title it should come under : Deployment or Testing

**Comment by elinguiuriel** [comment]
Go ahead, please !
