### ISSUE TITLE
Enhance the getting started Documentation

### ISSUE THREAD

**Issue by elinguiuriel** [fbdevelopercircles/open-source-edu-bot#7]
Enhance the documentation in the README.md to be easy to follow by new contributor like : https://developers.facebook.com/docs/messenger-platform/getting-started/sample-apps/original-coast-clothing

**Comment by aboullaite** [comment]
@elinguiuriel Can you add more details to this issue! Something like a checklist of the enhancement you want to be added could help contributors to grasp what's needed

**Comment by ankitaggarwal23** [comment]
Can I contribute in this project

**Comment by elinguiuriel** [comment]
@ankitaggarwal23 please yourself! 👍
