### ISSUE TITLE
Reword prompt that asks about version control

### ISSUE THREAD

**Issue by caabernathy** [fbdevelopercircles/open-source-edu-bot#8]
#### Is your feature request related to a problem? Please describe.
A slight improvement in grammar could be made for one of the prompts. See below:

![Screen Shot 2020-07-16 at 8 46 05 AM](https://user-images.githubusercontent.com/691109/87678650-d09ce900-c740-11ea-92c3-9126772490d9.png)

The phrase "version control tools" doesn't seem quite right in this context.

#### Describe the solution you'd like

A suggestion is to change the sentence to :
"An important component in Open Source contribution is version control."

**Comment by vj-codes** [comment]
I would like to fix this @caabernathy @aboullaite

**Comment by vj-codes** [comment]
@aboullaite sorry to ping again but may I work on this?

**Comment by aboullaite** [comment]
Oh sorry @vj-codes! I missed this one! Yes sure, thanks for helping on this. I assigned it to you
