### ISSUE TITLE
Update Code of conduct link in Readme.md

### ISSUE THREAD

**Issue by vj-codes** [fbdevelopercircles/open-source-edu-bot#92]
#### Describe the bug
The code of conduct link in readme takes the user to the main facebook page https://engineering.fb.com/codeofconduct/.
However this repository has the same as a separate .md file [here](https://github.com/fbdevelopercircles/open-source-edu-bot/blob/master/CODE_OF_CONDUCT.md) and the link should take the user to the file within the repo and not the other one.

**Comment by vj-codes** [comment]
May I work on this ? @aboullaite @elinguiuriel

**Comment by elinguiuriel** [comment]
@vj-codes please yourself 👍
