### ISSUE TITLE
Improve setup instructions

### ISSUE THREAD

**Issue by vj-codes** [fbdevelopercircles/open-source-edu-bot#98]
#### Describe the bug
git clone https://github.com/fbdevelopercircles/open-source-edu-bot should be changed to
git clone https://github.com/fbdevelopercircles/YOUR_GITHUB_USER_NAME/open-source-edu-bot (not a link )

And git remote , command to check if git remote works should be added to help users contribute .

**Comment by vj-codes** [comment]
@aboullaite may I work on this?

**Comment by aboullaite** [comment]
Go ahead 👍
